# Most fundamental concepts of tensors using tensorflow

Topics that gonna be covered-
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensor & numpy
* Using @tf.function (a way to speed up regular python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to sharpen skill

## Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.5.0


* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers(when n can be any number,a 0-dimensional tensor is a scalar,a 1-dimensional tensor is a vector)

# Constant/unchanged tensors which means we can't update tensor elements

In [2]:
# Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Checking the no. of dimensions of a tensor(ndim stands for no. of dimensions)
scalar.ndim

0

In [4]:
# Creating a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of the vector
vector.ndim

1

In [6]:
# Create a matrix(has more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16) #specify the datatype with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

# Variable tensor/changeable tensor

In [12]:
changeable_tensor=tf.Variable([10,7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [13]:
# Change the first element of the vector
print(changeable_tensor[0])
changeable_tensor[0].assign(3)
changeable_tensor

tf.Tensor(10, shape=(), dtype=int32)


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 7], dtype=int32)>

# Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers

In [14]:
# Create 2 random tensors(but the same)
random_1=tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [15]:
random_3=tf.random.Generator.from_seed(7)
random_3=random_3.normal(shape=(3,2))
random_2, random_3, random_2==random_3

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# Shuffle the order of elements in a tensor
It lools like if we want our shuffled tensors to be in the same order,we've got to use the global level random seed as well as the operation level random seed:

> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the reandom sequence."

In [16]:
not_shuffled1=tf.random.Generator.from_seed(42)
not_shuffled1=not_shuffled1.normal(shape=(3,2))
not_shuffled1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [17]:
# Shuffle our non-shuffled tensor
print(tf.random.shuffle(not_shuffled1))

tf.Tensor(
[[ 0.07595026 -1.2573844 ]
 [-0.7565803  -0.06854702]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [18]:
tf.random.set_seed(4) # global level random seed
tf.random.shuffle(not_shuffled1,seed=4) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [19]:
tf.random.set_seed(4)
tf.random.shuffle(not_shuffled1,seed=5)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193765, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

# Other ways to make tensors

In [20]:
tf.ones([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
tf.zeros(shape=(4,3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

# Turn Numpy arrays into tensors

The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [22]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
A=tf.constant(numpy_A)
B=tf.constant(numpy_A,shape=(2,3,4))
A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [24]:
A.ndim, B.ndim

(1, 3)

# Getting information from tensors
Important attributes of tensors:
* Shape
* Rank
* Axis or dimension
* Size

In [25]:
# Create a rank 4 tensor(4 dimensions)
rank4_tensor=tf.zeros(shape=(2,3,4,5))
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
# Get various attributes of tensor
print('Datatype of every element:',rank4_tensor.dtype)
print('Number of dimensions(rank):',rank4_tensor.ndim)
print('Shape of tensor:',rank4_tensor.shape)
print('Elements along the 0 axis:',rank4_tensor.shape[0])
print('Elements along the last axis:',rank4_tensor.shape[-1])
print('Total no. of elements in tensor:',tf.size(rank4_tensor))
print('Total no. of elements in tensor after converting to numpy:',tf.size(rank4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total no. of elements in tensor: tf.Tensor(120, shape=(), dtype=int32)
Total no. of elements in tensor after converting to numpy: 120


# Indexing tensors
Tensors can be indexed just like python lists

In [27]:
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# Get the first 2 elements of each dimension
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
# Get the first element from each dimension from each index except for the final one
print(rank4_tensor.shape)
rank4_tensor[:1,:1,:1,:]

(2, 3, 4, 5)


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
# Get the first element from each dimension from each index except for the 2nd last one
print(rank4_tensor.shape)
rank4_tensor[:1,:1,:,:1]

(2, 3, 4, 5)


<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [31]:
# Create a rank 2 tensor (2 dimensions)
rank2_tensor=tf.constant([[10,6],
                          [5,2]])
rank2_tensor.shape,rank2_tensor.ndim

(TensorShape([2, 2]), 2)

In [32]:
# Get the last item for each row 
rank2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 2], dtype=int32)>

# Add extra dimension to tensors

In [33]:
rank3_tensor=rank2_tensor[...,tf.newaxis] # add extra dimension to last.[:,:,tf.newaxis] is also applicable
rank2_tensor,rank3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  6],
        [ 5,  2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 6]],
 
        [[ 5],
         [ 2]]], dtype=int32)>)

In [34]:
# Alternative to tf.newaxis
tf.expand_dims(rank2_tensor,axis=-1) # add dimension to last as -1 index is used

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 6]],

       [[ 5],
        [ 2]]], dtype=int32)>

In [35]:
tf.expand_dims(rank2_tensor,axis=0) # add dimension to first as  index is used

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  6],
        [ 5,  2]]], dtype=int32)>

# Manipulating tensors(tensor operations)
**Basic Operations**
`+`,`-`,`*`,`/`

In [36]:
tensor=tf.constant([[10,2],
                   [4,6]])
print(tensor)
print('\nAddition:\n',tensor+10)
print('\nSubtraction:\n',tensor-10)
print('\nMultiplication:\n',tensor*10)
print('\nDivision:\n',tensor/10)

tf.Tensor(
[[10  2]
 [ 4  6]], shape=(2, 2), dtype=int32)

Addition:
 tf.Tensor(
[[20 12]
 [14 16]], shape=(2, 2), dtype=int32)

Subtraction:
 tf.Tensor(
[[ 0 -8]
 [-6 -4]], shape=(2, 2), dtype=int32)

Multiplication:
 tf.Tensor(
[[100  20]
 [ 40  60]], shape=(2, 2), dtype=int32)

Division:
 tf.Tensor(
[[1.  0.2]
 [0.4 0.6]], shape=(2, 2), dtype=float64)


In [37]:
# tensorflow built-in function can also be used, it's better to use tf functions as it supports gpu
print(tensor)
print('\nAddition using tensorflow built-in function:\n',tf.add(tensor,10))
print('\nSubtraction using tensorflow built-in function:\n',tf.subtract(tensor,10))
print('\nMultiplication using tensorflow built-in function:\n',tf.multiply(tensor,10))
print('\nDivision using tensorflow built-in function:\n',tf.divide(tensor,10))

tf.Tensor(
[[10  2]
 [ 4  6]], shape=(2, 2), dtype=int32)

Addition using tensorflow built-in function:
 tf.Tensor(
[[20 12]
 [14 16]], shape=(2, 2), dtype=int32)

Subtraction using tensorflow built-in function:
 tf.Tensor(
[[ 0 -8]
 [-6 -4]], shape=(2, 2), dtype=int32)

Multiplication using tensorflow built-in function:
 tf.Tensor(
[[100  20]
 [ 40  60]], shape=(2, 2), dtype=int32)

Division using tensorflow built-in function:
 tf.Tensor(
[[1.  0.2]
 [0.4 0.6]], shape=(2, 2), dtype=float64)


# Matrix Multiplication

In [38]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  2]
 [ 4  6]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[108,  32],
       [ 64,  44]], dtype=int32)>

In [39]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,   4],
       [ 16,  36]], dtype=int32)>

In [40]:
# Matrix multiplication with python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[108,  32],
       [ 64,  44]], dtype=int32)>

In [41]:
X=tf.constant(np.random.randint(10,size=(3,2)))
Y=tf.constant(np.random.randint(10,size=(3,2)))
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[5, 8],
        [9, 4],
        [4, 6]])>, <tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[3, 1],
        [3, 7],
        [1, 9]])>)

In [42]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[23, 71, 77],
       [31, 55, 45],
       [18, 54, 58]])>

In [43]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[71, 13, 87],
       [55, 13, 63],
       [54, 10, 66]])>

In [44]:
print('Normal Y:\n',Y)
print('\nReshaped Y:\n',tf.reshape(Y,shape=(2,3)))
print('\nTransposed Y:\n',tf.transpose(Y))

Normal Y:
 tf.Tensor(
[[3 1]
 [3 7]
 [1 9]], shape=(3, 2), dtype=int64)

Reshaped Y:
 tf.Tensor(
[[3 1 3]
 [7 1 9]], shape=(2, 3), dtype=int64)

Transposed Y:
 tf.Tensor(
[[3 3 1]
 [1 7 9]], shape=(2, 3), dtype=int64)


# Changing the datatype of a tensor

In [45]:
# Create a new tensor with default datatype
B=tf.constant([4.6,2.4])
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.6, 2.4], dtype=float32)>,
 tf.float32)

In [46]:
C=tf.constant([10,6])
C.dtype

tf.int32

In [47]:
# Change from float32 to float16 (reduced precision)
D=tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([4.6, 2.4], dtype=float16)>,
 tf.float16)

In [48]:
# Change from int32 to float32
E=tf.cast(C,dtype=tf.float32)
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  6.], dtype=float32)>,
 tf.float32)

# Aggregating tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [49]:
D=tf.constant([-10,-8])
tf.size(D),D.ndim,D.shape,D

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 1,
 TensorShape([2]),
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([-10,  -8], dtype=int32)>)

In [50]:
# Get the absolute values of tensor
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>

# Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [51]:
E=tf.constant(np.random.randint(0,100,size=50))
tf.size(E),E.shape,E.ndim,E

(<tf.Tensor: shape=(), dtype=int32, numpy=50>,
 TensorShape([50]),
 1,
 <tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([ 5, 35, 90, 98, 24, 12, 88, 14, 67,  5, 85, 18, 66, 34, 61, 19,  4,
        87, 81,  3, 39, 48, 59, 66, 23,  3,  8, 32, 44,  3,  8, 88, 98, 18,
        34, 73,  8, 45,  7, 28, 31, 83, 43, 43, 16, 74,  8, 34, 48,  0])>)

In [52]:
print('Minimum of tensor E:',tf.reduce_min(E))
print('Maximum of tensor E:',tf.reduce_max(E))
print('Mean of tensor E:',tf.reduce_mean(E))
print('Sum of tensor E:',tf.reduce_sum(E))

Minimum of tensor E: tf.Tensor(0, shape=(), dtype=int64)
Maximum of tensor E: tf.Tensor(98, shape=(), dtype=int64)
Mean of tensor E: tf.Tensor(40, shape=(), dtype=int64)
Sum of tensor E: tf.Tensor(2008, shape=(), dtype=int64)


**Exercise:** Find the variance and standard deviation of `E` tensor using tensorflow methods.

In [53]:
import tensorflow_probability as tfp

In [54]:
print('Variance of tensor E:',tfp.stats.variance(E)) # Won't work with reduce_ method
print('Standard deviation of tensor E:',tf.math.reduce_std(tf.cast(E,dtype=tf.float32))) # work with only real or complex no.,so typecast has been done

Variance of tensor E: tf.Tensor(919, shape=(), dtype=int64)
Standard deviation of tensor E: tf.Tensor(30.319868, shape=(), dtype=float32)


In [55]:
# Variance can also be found using tf.reduce_ method, sorry for the incovenience but before that we must include .math
print('Variance of tensor E:',tf.math.reduce_variance(tf.cast(E,dtype=tf.float32)))

Variance of tensor E: tf.Tensor(919.2944, shape=(), dtype=float32)


# Find the positional maximum and minimum

In [56]:
tf.random.set_seed(42)
U=tf.random.uniform(shape=(50,))
U

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [57]:
# Find the positional maximum
print('Index of positional maximum:',tf.argmax(U))
print('Value at the index of positional maximum:',U[tf.argmax(U)])
print('Comparison with reduced method max:',U[tf.argmax(U)]==tf.reduce_max(U))

Index of positional maximum: tf.Tensor(42, shape=(), dtype=int64)
Value at the index of positional maximum: tf.Tensor(0.9671384, shape=(), dtype=float32)
Comparison with reduced method max: tf.Tensor(True, shape=(), dtype=bool)


In [58]:
# Find the positional minimum
print('Index of positional minimum:',tf.argmin(U))
print('Value at the index of positional minimum:',U[tf.argmin(U)])
print('Comparison with reduced method min:',U[tf.argmin(U)]==tf.reduce_min(U))

Index of positional minimum: tf.Tensor(16, shape=(), dtype=int64)
Value at the index of positional minimum: tf.Tensor(0.009463668, shape=(), dtype=float32)
Comparison with reduced method min: tf.Tensor(True, shape=(), dtype=bool)


# Squeezing a tensor (removing all single dimensions)

In [59]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=(50,)),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [60]:
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# One-hot encoding tensors

In [61]:
some_list=[0,1,2,3]
tf.one_hot(some_list,depth=4) # some_list_dim x depth

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# Squaring,log,square root

In [63]:
H=tf.range(1,10,delta=2)
H

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [69]:
print('Square of tensors:',tf.square(H))
print('Square root of tensors:',tf.sqrt(tf.cast(H,dtype=tf.float32)))
print('log of tensors:',tf.math.log(tf.cast(H,dtype=tf.float32)))

Square of tensors: tf.Tensor([ 1  9 25 49 81], shape=(5,), dtype=int32)
Square root of tensors: tf.Tensor([1.        1.7320508 2.236068  2.6457512 3.       ], shape=(5,), dtype=float32)
log of tensors: tf.Tensor([0.        1.0986123 1.609438  1.9459102 2.1972246], shape=(5,), dtype=float32)
