# Most fundamental concepts of tensors using tensorflow

Topics that gonna be covered-
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensor & numpy
* Using @tf.function (a way to speed up regular python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to sharpen skill

## Introduction to Tensors

In [84]:
import tensorflow as tf
print(tf.__version__)

2.5.0


* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers(when n can be any number,a 0-dimensional tensor is a scalar,a 1-dimensional tensor is a vector)

# Constant/unchanged tensors which means we can't update tensor elements

In [68]:
# Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [69]:
# Checking the no. of dimensions of a tensor(ndim stands for no. of dimensions)
scalar.ndim

0

In [70]:
# Creating a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [71]:
# check the dimension of the vector
vector.ndim

1

In [72]:
# Create a matrix(has more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [73]:
matrix.ndim

2

In [74]:
# create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16) #specify the datatype with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [75]:
another_matrix.ndim

2

In [76]:
# Create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [77]:
tensor.ndim

3

# Variable tensor/changeable tensor

In [78]:
changeable_tensor=tf.Variable([10,7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [79]:
# Change the first element of the vector
print(changeable_tensor[0])
changeable_tensor[0].assign(3)
changeable_tensor

tf.Tensor(10, shape=(), dtype=int32)


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 7], dtype=int32)>

# Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers

In [80]:
# Create 2 random tensors(but the same)
random_1=tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [81]:
random_3=tf.random.Generator.from_seed(7)
random_3=random_3.normal(shape=(3,2))
random_2, random_3, random_2==random_3

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# Shuffle the order of elements in a tensor

In [82]:
not_shuffled1=tf.random.Generator.from_seed(42)
not_shuffled1=not_shuffled1.normal(shape=(3,2))
not_shuffled2=tf.random.Generator.from_seed(20)
not_shuffled2=not_shuffled2.normal(shape=(3,2))
not_shuffled3=tf.random.Generator.from_seed(15)
not_shuffled3=not_shuffled3.normal(shape=(3,2))
not_shuffled4=tf.random.Generator.from_seed(5)
not_shuffled4=not_shuffled4.normal(shape=(3,2))
not_shuffled5=tf.random.Generator.from_seed(7)
not_shuffled5=not_shuffled5.normal(shape=(3,2))
not_shuffled1, not_shuffled2, not_shuffled3, not_shuffled4, not_shuffled5

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ],
        [ 0.86754173, -0.19625713],
        [-1.322665  , -0.02279496]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149976, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0278524 ,  0.27974114],
        [-0.01347923,  1.845181  ],
        [ 0.9706111 , -1.0242517 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>)

In [83]:
# Shuffle our non-shuffled tensor
print(tf.random.shuffle(not_shuffled1))
print(tf.random.shuffle(not_shuffled2))
print(tf.random.shuffle(not_shuffled3))
print(tf.random.shuffle(not_shuffled4))
print(tf.random.shuffle(not_shuffled5))

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 0.86754173 -0.19625713]
 [-1.322665   -0.02279496]
 [ 0.88051325 -1.6833194 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.63509274  0.3703566 ]
 [ 1.5222508   0.59303206]
 [ 0.33149976 -0.5445254 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 1.0278524   0.27974114]
 [ 0.9706111  -1.0242517 ]
 [-0.01347923  1.845181  ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.8757901  -0.08857017]
 [ 0.69211644  0.84215707]
 [-1.3240396   0.2878567 ]], shape=(3, 2), dtype=float32)


In [85]:
tf.random.set_seed(4)
tf.random.shuffle(not_shuffled1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [89]:
tf.random.set_seed(4)
tf.random.shuffle(not_shuffled1,seed=5)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193765, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [92]:
tf.random.set_seed(4)
tf.random.shuffle(not_shuffled1,seed=3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>