In [1]:
import tensorflow as tf
import numpy as np

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [9]:
vector=tf.constant([1,4,5])
scalar=tf.constant(30)
matrix=tf.constant(np.arange(1,11),shape=(5,2))
tensor=tf.constant(np.random.randint(1,size=20),shape=(2,2,5))
vector,scalar,matrix,tensor

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 5], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=30>,
 <tf.Tensor: shape=(5, 2), dtype=int64, numpy=
 array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])>,
 <tf.Tensor: shape=(2, 2, 5), dtype=int64, numpy=
 array([[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]])>)

2. Find the shape, rank and size of the tensors you created in 1.

In [12]:
def attributes_of_tensors(tensor,tensor_name):
  print(f'Shape of the {tensor_name}:{tensor.shape}')
  print(f'Rank of the {tensor_name}:{tf.rank(tensor)}')
  print(f'Size of the {tensor_name}:{tf.size(tensor)}')

In [13]:
attributes_of_tensors(vector,'vector')
attributes_of_tensors(scalar,'scalar')
attributes_of_tensors(matrix,'matrix')
attributes_of_tensors(tensor,'tensor')

Shape of the vector:(3,)
Rank of the vector:1
Size of the vector:3
Shape of the scalar:()
Rank of the scalar:0
Size of the scalar:1
Shape of the matrix:(5, 2)
Rank of the matrix:2
Size of the matrix:10
Shape of the tensor:(2, 2, 5)
Rank of the tensor:3
Size of the tensor:20


3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [20]:
tf.random.set_seed(42)
tensor1=tf.random.uniform(shape=[5,300])
tensor2=tf.random.uniform(shape=[5,300])
tensor1,tensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [28]:
tf.matmul(tensor1,tf.transpose(tensor2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33342 , 73.404976, 77.15962 , 73.98367 , 80.90054 ],
       [75.14636 , 68.80438 , 74.24302 , 71.84183 , 75.60205 ],
       [79.759415, 75.64456 , 77.797585, 74.74874 , 80.55982 ],
       [75.08525 , 69.06407 , 74.30776 , 72.27615 , 76.05669 ],
       [85.0569  , 74.266266, 78.00686 , 74.88679 , 83.134155]],
      dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [34]:
tf.tensordot(tensor1,tf.transpose(tensor2),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33342 , 73.404976, 77.15962 , 73.98367 , 80.90054 ],
       [75.14636 , 68.80438 , 74.24302 , 71.84183 , 75.60205 ],
       [79.759415, 75.64456 , 77.797585, 74.74874 , 80.55982 ],
       [75.08525 , 69.06407 , 74.30776 , 72.27615 , 76.05669 ],
       [85.0569  , 74.266266, 78.00686 , 74.88679 , 83.134155]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [42]:
tf.random.set_seed(42)
tensor3=tf.random.normal(shape=[224,224,3])
tensor3.shape

TensorShape([224, 224, 3])

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [50]:
print('Max value of tensor:',tf.reduce_max(tensor3))
print('Min value of tensor:',tf.reduce_min(tensor3))

Max value of tensor: tf.Tensor(4.486006, shape=(), dtype=float32)
Min value of tensor: tf.Tensor(-5.4462285, shape=(), dtype=float32)


8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [52]:
tf.random.set_seed(42)
tensor4=tf.random.normal(shape=[1,224,224,3])
tf.squeeze(tensor4).shape

TensorShape([224, 224, 3])

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [59]:
tf.random.set_seed(42)
tensor5=tf.constant(np.random.randint(0,10,size=10))
tensor5

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([9, 4, 5, 2, 7, 3, 4, 4, 0, 4])>

In [60]:
tf.argmax(tensor5)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

10. One-hot encode the tensor you created in 9.

In [62]:
tf.one_hot(tensor5,depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>