# Most fundamental concepts of tensors using tensorflow

Topics that gonna be covered-
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensor & numpy
* Using @tf.function (a way to speed up regular python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to sharpen skill

## Introduction to Tensors

In [4]:
import tensorflow as tf
print(tf.__version__)

2.5.0


* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers(when n can be any number,a 0-dimensional tensor is a scalar,a 1-dimensional tensor is a vector)

# Constant/unchanged tensors which means we can't update tensor elements

In [5]:
# Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Checking the no. of dimensions of a tensor(ndim stands for no. of dimensions)
scalar.ndim

0

In [7]:
# Creating a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# check the dimension of the vector
vector.ndim

1

In [9]:
# Create a matrix(has more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
# create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16) #specify the datatype with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [13]:
# Create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

# Variable tensor/changeable tensor

In [19]:
changeable_tensor=tf.Variable([10,7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [20]:
# Change the first element of the vector
print(changeable_tensor[0])
changeable_tensor[0].assign(3)
changeable_tensor

tf.Tensor(10, shape=(), dtype=int32)


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 7], dtype=int32)>